# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push an image to docker hub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/show/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Docker build and push image to dockerhub
      inputs:
        containerRegistry: 'OK-dockerhub-SC'
        repository: 'dfompo/graphish-show'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/show/Dockerfile'